import type { Metadata } from "next";
import "./globals.css";
import Client from "./client";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body>
				<Client />
				{children}
			</body>
		</html>
	);
}
